### ISSUE TITLE
add custom payloads

### ISSUE THREAD

**Issue by Acemampz** [Kostasssss/LFITester#7]
is it possible to add custom payloads? i tried the -m flag but i am getting an error "invalid int value" . 

lfitester -u "http://domain.com/test.php?view=" -v --mode lfipayload.txt

i have a text file with the required payload and want to use this payload against the link i am testing with, this is the payload i want to use, https://github.com/rezaJOY/Local-File-Inclusion-Payloads/blob/main/lfi%20payload.txt

**Comment by Konstantinos-Papanagnou** [comment]
Just for a clarification in order to get the terminology down right, this is not the payloads, but the poc. The poc is used only for the verification of the exploit (whereas the payloads are for the RCE) and that is done manually and hardcoded through code currently (hence the functionality exists). I will create a new pull request for this from my local branch and @kostas-pa will approve it when he can. Up until that point you can hardcode it in the PayloadManager.py file.

Also @kostas-pa, please do reject this pull request referenced to this issue as it's not fixing this particular issue.

**Comment by Konstantinos-Papanagnou** [comment]
Approve the pull request and the issue should be marked completed. :)
